import 'dart:convert';

import '../agent_manifest.dart';
import 'emitter_utils.dart';

/// Emits Windows App Actions URI-launch registration.
///
/// Opt-in via [AgentManifestSurface.windowsAppActions]. Primitive parameters
/// become Text entities. The single output `result` is `AgentResult` JSON.
/// Nested schemas fail the emit. This is not protocol-activation fallback and
/// not an Agent Launcher.
final class WindowsAppActionsEmitter {
  const WindowsAppActionsEmitter({this.protocolScheme});

  final String? protocolScheme;

  static const registrationFileName = 'intentcall_app_actions.json';
  static const manifestFragmentFileName = 'intentcall_app_actions_manifest.xml';

  String? emitRegistration(final AgentManifest manifest) {
    final actions = _actions(manifest);
    if (actions == null) {
      return null;
    }
    return '${const JsonEncoder.withIndent('  ').convert(<String, Object?>{'version': 3, 'actions': actions})}\n';
  }

  String? emitManifestFragment(final AgentManifest manifest) {
    final actions = _actions(manifest);
    if (actions == null) {
      return null;
    }
    final scheme = _scheme(manifest);
    return '''
<!-- Generated by intentcall_platform — do not edit by hand. -->
<!-- Package identity is required. Unpackaged Flutter Windows builds cannot register App Actions. -->
<Extensions>
  <uap:Extension Category="windows.protocol">
    <uap:Protocol Name="$scheme" ReturnResults="always">
      <uap:DisplayName>IntentCall App Actions</uap:DisplayName>
    </uap:Protocol>
  </uap:Extension>
  <uap3:Extension Category="windows.appExtension">
    <uap3:AppExtension Name="com.microsoft.windows.ai.actions" DisplayName="IntentCall" Id="IntentCallActions" PublicFolder="Assets">
      <uap3:Properties>
        <Registration xmlns="">$registrationFileName</Registration>
      </uap3:Properties>
    </uap3:AppExtension>
  </uap3:Extension>
</Extensions>
''';
  }

  String _scheme(final AgentManifest manifest) => requireProtocolScheme(
    protocolScheme ?? manifest.protocolScheme,
    artifact: 'Windows App Actions registration',
  );

  List<Map<String, Object?>>? _actions(final AgentManifest manifest) {
    final tools = manifest.tools
        .where(
          (final tool) =>
              tool.kind.name == 'tool' &&
              tool.surfaces.includes(
                AgentManifestSurface.windowsAppActions,
                defaultValue: false,
              ),
        )
        .toList(growable: false);
    if (tools.isEmpty) {
      return null;
    }
    final scheme = _scheme(manifest);
    return [for (final tool in tools) _action(tool, scheme)];
  }

  Map<String, Object?> _action(
    final AgentManifestEntry tool,
    final String scheme,
  ) {
    final fields = _textFields(tool);
    final requiredNames = fields
        .where((final field) => field.required)
        .map((final field) => field.name)
        .toList(growable: false);
    final combination = requiredNames.isEmpty
        ? fields.map((final field) => field.name).toList(growable: false)
        : requiredNames;
    return <String, Object?>{
      'id': tool.qualifiedName,
      'description': tool.description.isEmpty
          ? tool.qualifiedName
          : tool.description,
      'icon': 'ms-resource://Files/Assets/AppIcon.png',
      'usesGenerativeAI': false,
      'allowedAppInvokers': <String>['*'],
      'inputs': [
        for (final field in fields)
          <String, Object?>{
            'name': field.name,
            'kind': 'Text',
            'required': field.required,
          },
      ],
      'inputCombinations': [
        <String, Object?>{
          'inputs': combination,
          'description': tool.description.isEmpty
              ? tool.qualifiedName
              : tool.description,
        },
      ],
      'outputs': <Map<String, Object?>>[
        <String, Object?>{'name': 'result', 'kind': 'Text'},
      ],
      'invocation': <String, Object?>{
        'type': 'Uri',
        'uri': '$scheme://actions/${tool.qualifiedName}',
        'inputData': <String, Object?>{
          for (final field in fields) field.name: '\${${field.name}.Text}',
        },
      },
    };
  }

  List<_TextField> _textFields(final AgentManifestEntry tool) {
    final schema = tool.inputSchema;
    final type = schema['type'];
    if (type != null && type != 'object') {
      throw UnsupportedError(
        'Windows App Actions support an object input schema for '
        '${tool.qualifiedName}; found "$type".',
      );
    }
    final properties = schema['properties'];
    if (properties == null) {
      return const <_TextField>[];
    }
    if (properties is! Map) {
      throw UnsupportedError(
        'Windows App Actions input properties for ${tool.qualifiedName} '
        'must be an object.',
      );
    }
    final rawRequired = schema['required'];
    final required = <String>{
      ...(rawRequired is List ? rawRequired : const <Object?>[])
          .whereType<String>(),
    };
    final fields = <_TextField>[];
    for (final entry in properties.entries) {
      final name = '${entry.key}';
      final child = entry.value;
      if (child is! Map) {
        throw UnsupportedError(
          'Windows App Actions parameter "$name" on ${tool.qualifiedName} '
          'must be a schema object.',
        );
      }
      final childType = '${child['type']}';
      if (childType != 'string' &&
          childType != 'integer' &&
          childType != 'number' &&
          childType != 'boolean') {
        throw UnsupportedError(
          'Windows App Actions support only primitive string, integer, '
          'number, or boolean parameters in ${tool.qualifiedName}; "$name" '
          'has unsupported type "$childType".',
        );
      }
      fields.add(_TextField(name: name, required: required.contains(name)));
    }
    return fields;
  }
}

final class _TextField {
  const _TextField({required this.name, required this.required});

  final String name;
  final bool required;
}
