library;

export 'src/agent_manifest.dart';
export 'src/bootstrap/agent_web_mcp_bootstrap.dart';
export 'src/catalog/agent_registry_catalog.dart';
export 'src/catalog/catalog_loader.dart';
export 'src/catalog/project_utils.dart';
export 'src/emitters/android_shortcuts_xml_emitter.dart';
export 'src/emitters/apple_app_intents_testing_emitter.dart';
export 'src/emitters/apple_dart_extension_inline_emitter.dart';
export 'src/emitters/apple_swift_app_intents_emitter.dart';
export 'src/emitters/linux_desktop_entry_emitter.dart';
export 'src/emitters/web_manifest_emitter.dart';
export 'src/emitters/web_mcp_js_emitter.dart';
export 'src/emitters/windows_protocol_emitter.dart';
export 'src/init/platform_hooks_init.dart';
export 'src/invocation/intentcall_entity_open.dart';
export 'src/invocation/intentcall_invocation.dart';
export 'src/projection/manifest_exporter.dart';
export 'src/projection/projection_platforms.dart';
export 'src/projection/manifest_merger.dart';
export 'src/projection/manifest_surface_index.dart';
export 'src/projection/projection_policy.dart';
export 'src/sync/platform_sync.dart';
export 'src/templates/platform_hook_spine.dart';
export 'src/templates/platform_hook_templates.dart';
