// Autogenerated from Pigeon (v26.3.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


/// Native invocation envelope drained from the handoff store.
class IntentCallInvocationEnvelopeDto {
  IntentCallInvocationEnvelopeDto({
    required this.id,
    required this.qualifiedName,
    this.arguments,
    required this.source,
    required this.createdAt,
  });

  String id;

  String qualifiedName;

  Map<String?, Object?>? arguments;

  String source;

  String createdAt;

  List<Object?> _toList() {
    return <Object?>[
      id,
      qualifiedName,
      arguments,
      source,
      createdAt,
    ];
  }

  Object encode() {
    return _toList();  }

  static IntentCallInvocationEnvelopeDto decode(Object result) {
    result as List<Object?>;
    return IntentCallInvocationEnvelopeDto(
      id: result[0]! as String,
      qualifiedName: result[1]! as String,
      arguments: (result[2] as Map<Object?, Object?>?)?.cast<String?, Object?>(),
      source: result[3]! as String,
      createdAt: result[4]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! IntentCallInvocationEnvelopeDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) && _deepEquals(qualifiedName, other.qualifiedName) && _deepEquals(arguments, other.arguments) && _deepEquals(source, other.source) && _deepEquals(createdAt, other.createdAt);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// Native entity-open envelope drained from the entity snapshot store.
class IntentCallEntityOpenEnvelopeDto {
  IntentCallEntityOpenEnvelopeDto({
    required this.id,
    required this.entityType,
    required this.entityId,
    required this.source,
    required this.createdAt,
  });

  String id;

  String entityType;

  String entityId;

  String source;

  String createdAt;

  List<Object?> _toList() {
    return <Object?>[
      id,
      entityType,
      entityId,
      source,
      createdAt,
    ];
  }

  Object encode() {
    return _toList();  }

  static IntentCallEntityOpenEnvelopeDto decode(Object result) {
    result as List<Object?>;
    return IntentCallEntityOpenEnvelopeDto(
      id: result[0]! as String,
      entityType: result[1]! as String,
      entityId: result[2]! as String,
      source: result[3]! as String,
      createdAt: result[4]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! IntentCallEntityOpenEnvelopeDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) && _deepEquals(entityType, other.entityType) && _deepEquals(entityId, other.entityId) && _deepEquals(source, other.source) && _deepEquals(createdAt, other.createdAt);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}

/// Manifest-projected entity field keys for snapshot CRUD and search.
class IntentCallEntityKeyBundle {
  IntentCallEntityKeyBundle({
    this.idKey = 'id',
    this.titleKey = 'title',
    this.subtitleKey = 'subtitle',
    this.keywordsKey = 'keywords',
  });

  String idKey;

  String titleKey;

  String subtitleKey;

  String keywordsKey;

  List<Object?> _toList() {
    return <Object?>[
      idKey,
      titleKey,
      subtitleKey,
      keywordsKey,
    ];
  }

  Object encode() {
    return _toList();  }

  static IntentCallEntityKeyBundle decode(Object result) {
    result as List<Object?>;
    return IntentCallEntityKeyBundle(
      idKey: result[0]! as String,
      titleKey: result[1]! as String,
      subtitleKey: result[2]! as String,
      keywordsKey: result[3]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! IntentCallEntityKeyBundle || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(idKey, other.idKey) && _deepEquals(titleKey, other.titleKey) && _deepEquals(subtitleKey, other.subtitleKey) && _deepEquals(keywordsKey, other.keywordsKey);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is IntentCallInvocationEnvelopeDto) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    }    else if (value is IntentCallEntityOpenEnvelopeDto) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is IntentCallEntityKeyBundle) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return IntentCallInvocationEnvelopeDto.decode(readValue(buffer)!);
      case 130:
        return IntentCallEntityOpenEnvelopeDto.decode(readValue(buffer)!);
      case 131:
        return IntentCallEntityKeyBundle.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class IntentCallInvocationsHostApi {
  /// Constructor for [IntentCallInvocationsHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  IntentCallInvocationsHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<List<IntentCallInvocationEnvelopeDto>> takePendingInvocations() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.intentcall_bridge.IntentCallInvocationsHostApi.takePendingInvocations$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<IntentCallInvocationEnvelopeDto>();
  }
}

class IntentCallEntitiesHostApi {
  /// Constructor for [IntentCallEntitiesHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  IntentCallEntitiesHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<int> upsertEntitySnapshots(String entityType, List<Map<String?, Object?>> snapshots, IntentCallEntityKeyBundle keys) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.intentcall_bridge.IntentCallEntitiesHostApi.upsertEntitySnapshots$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[entityType, snapshots, keys]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as int;
  }

  Future<int> deleteEntitySnapshots(String entityType, List<String> ids, IntentCallEntityKeyBundle keys) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.intentcall_bridge.IntentCallEntitiesHostApi.deleteEntitySnapshots$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[entityType, ids, keys]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as int;
  }

  Future<int> clearEntityTypeSnapshots(String entityType) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.intentcall_bridge.IntentCallEntitiesHostApi.clearEntityTypeSnapshots$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[entityType]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as int;
  }

  Future<List<Map<String?, Object?>>> listEntitySnapshots(String entityType) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.intentcall_bridge.IntentCallEntitiesHostApi.listEntitySnapshots$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[entityType]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<Map<String?, Object?>>();
  }

  Future<List<Map<String?, Object?>>> searchEntitySnapshots(String entityType, String query, int limit, IntentCallEntityKeyBundle keys) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.intentcall_bridge.IntentCallEntitiesHostApi.searchEntitySnapshots$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[entityType, query, limit, keys]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<Map<String?, Object?>>();
  }

  Future<List<IntentCallEntityOpenEnvelopeDto>> takePendingEntityOpens() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.intentcall_bridge.IntentCallEntitiesHostApi.takePendingEntityOpens$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<IntentCallEntityOpenEnvelopeDto>();
  }
}
