import 'package:intentcall_platform/intentcall_platform.dart';
import 'package:test/test.dart';

void main() {
  final manifest = AgentManifest.fromJson(<String, Object?>{
    'version': 1,
    'platform': 'android',
    'shortcuts': [
      <String, Object?>{
        'qualifiedName': 'app_cart_total',
        'namespace': 'app',
        'name': 'cart_total',
        'description': 'Return cart total',
        'kind': 'tool',
        'inputSchema': <String, Object?>{
          'type': 'object',
          'required': <String>['currency'],
          'properties': <String, Object?>{
            'currency': <String, Object?>{'type': 'string'},
            'includeTax': <String, Object?>{'type': 'boolean'},
          },
        },
      },
    ],
  });

  group('AndroidShortcutsXmlEmitter', () {
    test('emits shortcut with intentcall deep link', () {
      final xml = const AndroidShortcutsXmlEmitter().emit(manifest);
      expect(xml, contains('android:shortcutId="app_cart_total"'));
      expect(xml, contains('intentcall://invoke/app_cart_total'));
      expect(xml, contains('Cart Total'));
    });

    test('matches golden xml', () {
      final xml = const AndroidShortcutsXmlEmitter().emit(manifest);
      expect(xml.trim(), _goldenAndroidShortcutsXml.trim());
    });
  });

  group('AppleSwiftAppIntentsEmitter', () {
    test('emits AppIntent and AppShortcutsProvider', () {
      final swift = const AppleSwiftAppIntentsEmitter().emit(manifest);
      expect(swift, contains('struct AppCartTotalIntent: AppIntent'));
      expect(swift, contains('@Parameter(title: "Currency")'));
      expect(swift, contains('var currency: String'));
      expect(swift, contains('var includeTax: Bool?'));
      expect(swift, contains('arguments["currency"] = currency'));
      expect(swift, contains('IntentCallShortcutsProvider'));
      expect(swift, contains('IntentCallNativeBridge'));
      expect(swift, contains('intentcall.pending_invocations'));
      expect(swift, contains('intentcall://invoke/'));
    });

    test('matches golden swift', () {
      final swift = const AppleSwiftAppIntentsEmitter().emit(manifest);
      expect(swift.trim(), _goldenAppleSwift.trim());
    });
  });

  group('LinuxDesktopEntryEmitter', () {
    test('registers x-scheme-handler', () {
      final desktop = const LinuxDesktopEntryEmitter().emit(manifest);
      expect(desktop, contains('x-scheme-handler/intentcall'));
      expect(desktop, contains('tool: app_cart_total'));
    });

    test('matches golden desktop entry', () {
      final desktop = const LinuxDesktopEntryEmitter().emit(manifest);
      expect(desktop.trim(), _goldenLinuxDesktop.trim());
    });
  });

  group('WindowsProtocolEmitter', () {
    test('emits registry script', () {
      final reg = const WindowsProtocolEmitter().emit(manifest);
      expect(reg, contains(r'[HKEY_CURRENT_USER\Software\Classes\intentcall]'));
      expect(reg, contains('; tool: app_cart_total'));
    });

    test('emits msix fragment', () {
      final msix = const WindowsProtocolEmitter().emitMsixFragment(manifest);
      expect(msix, contains('windows.protocol'));
      expect(msix, contains('Name="intentcall"'));
    });
  });
}

const _goldenAndroidShortcutsXml = '''
<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by intentcall_platform — do not edit by hand. -->
<shortcuts xmlns:android="http://schemas.android.com/apk/res/android">
  <shortcut
      android:shortcutId="app_cart_total"
      android:enabled="true"
      android:shortcutShortLabel="Cart Total"
      android:shortcutLongLabel="Return cart total">
    <intent
        android:action="android.intent.action.VIEW"
        android:data="intentcall://invoke/app_cart_total" />
  </shortcut>
</shortcuts>''';

const _goldenAppleSwift = r'''
// Generated by intentcall_platform — do not edit by hand.
import AppIntents
import Foundation
#if canImport(UIKit)
import UIKit
#elseif canImport(AppKit)
import AppKit
#endif

@available(iOS 16.0, macOS 13.0, *)
struct AppCartTotalIntent: AppIntent {
  static var title: LocalizedStringResource = "Return cart total"

  @Parameter(title: "Currency")
  var currency: String

  @Parameter(title: "IncludeTax")
  var includeTax: Bool?

  func perform() async throws -> some IntentResult {
    var arguments: [String: Any] = [:]
    arguments["currency"] = currency
    if let value = includeTax { arguments["includeTax"] = value }
    await IntentCallNativeBridge.enqueue(qualifiedName: "app_cart_total", arguments: arguments)
    return .result()
  }
}

@available(iOS 16.0, macOS 13.0, *)
struct IntentCallShortcutsProvider: AppShortcutsProvider {
  static var appShortcuts: [AppShortcut] {
    AppShortcut(intent: AppCartTotalIntent(), phrases: ["\(.applicationName) Cart Total"])
  }
}

enum IntentCallNativeBridge {
  private static let pendingKey = "intentcall.pending_invocations"

  static func enqueue(qualifiedName: String, arguments: [String: Any]) async {
    var pending = UserDefaults.standard.array(forKey: pendingKey) as? [[String: Any]] ?? []
    pending.append([
      "id": UUID().uuidString,
      "qualifiedName": qualifiedName,
      "arguments": arguments,
      "source": "native.generated",
      "createdAt": ISO8601DateFormatter().string(from: Date())
    ])
    UserDefaults.standard.set(pending, forKey: pendingKey)
    guard let url = URL(string: "intentcall://invoke/\(qualifiedName)") else { return }
    #if canImport(UIKit)
    await UIApplication.shared.open(url)
    #elseif canImport(AppKit)
    NSWorkspace.shared.open(url)
    #endif
  }
}''';

const _goldenLinuxDesktop = '''
# Generated by intentcall_platform — do not edit by hand.
# tool: app_cart_total
[Desktop Entry]
Type=Application
Name=Flutter App (IntentCall)
Comment=IntentCall deep-link handler
Exec=@EXEC@ %u
MimeType=x-scheme-handler/intentcall;
NoDisplay=true
Terminal=false''';
