// Autogenerated from Pigeon (v26.3.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

private func doubleEqualsIntentCallPlatformBridge(_ lhs: Double, _ rhs: Double) -> Bool {
  return (lhs.isNaN && rhs.isNaN) || lhs == rhs
}

private func doubleHashIntentCallPlatformBridge(_ value: Double, _ hasher: inout Hasher) {
  if value.isNaN {
    hasher.combine(0x7FF8000000000000)
  } else {
    // Normalize -0.0 to 0.0
    hasher.combine(value == 0 ? 0 : value)
  }
}

func deepEqualsIntentCallPlatformBridge(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
    return true

  case is (Void, Void):
    return true

  case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !deepEqualsIntentCallPlatformBridge(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsArray, let rhsArray) as ([Double], [Double]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !doubleEqualsIntentCallPlatformBridge(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard lhsDictionary.count == rhsDictionary.count else { return false }
    for (lhsKey, lhsValue) in lhsDictionary {
      var found = false
      for (rhsKey, rhsValue) in rhsDictionary {
        if deepEqualsIntentCallPlatformBridge(lhsKey, rhsKey) {
          if deepEqualsIntentCallPlatformBridge(lhsValue, rhsValue) {
            found = true
            break
          } else {
            return false
          }
        }
      }
      if !found { return false }
    }
    return true

  case (let lhs as Double, let rhs as Double):
    return doubleEqualsIntentCallPlatformBridge(lhs, rhs)

  case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
    return lhsHashable == rhsHashable

  default:
    return false
  }
}

func deepHashIntentCallPlatformBridge(value: Any?, hasher: inout Hasher) {
  let cleanValue = nilOrValue(value) as Any?
  if let cleanValue = cleanValue {
    if let doubleValue = cleanValue as? Double {
      doubleHashIntentCallPlatformBridge(doubleValue, &hasher)
    } else if let valueList = cleanValue as? [Any?] {
      for item in valueList {
        deepHashIntentCallPlatformBridge(value: item, hasher: &hasher)
      }
    } else if let valueList = cleanValue as? [Double] {
      for item in valueList {
        doubleHashIntentCallPlatformBridge(item, &hasher)
      }
    } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
      var result = 0
      for (key, value) in valueDict {
        var entryKeyHasher = Hasher()
        deepHashIntentCallPlatformBridge(value: key, hasher: &entryKeyHasher)
        var entryValueHasher = Hasher()
        deepHashIntentCallPlatformBridge(value: value, hasher: &entryValueHasher)
        result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
      }
      hasher.combine(result)
    } else if let hashableValue = cleanValue as? AnyHashable {
      hasher.combine(hashableValue)
    } else {
      hasher.combine(String(describing: cleanValue))
    }
  } else {
    hasher.combine(0)
  }
}


/// Native invocation envelope drained from the handoff store.
///
/// Generated class from Pigeon that represents data sent in messages.
struct IntentCallInvocationEnvelopeDto: Hashable {
  var id: String
  var qualifiedName: String
  var arguments: [String?: Any?]? = nil
  var source: String
  var createdAt: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> IntentCallInvocationEnvelopeDto? {
    let id = pigeonVar_list[0] as! String
    let qualifiedName = pigeonVar_list[1] as! String
    let arguments: [String?: Any?]? = nilOrValue(pigeonVar_list[2])
    let source = pigeonVar_list[3] as! String
    let createdAt = pigeonVar_list[4] as! String

    return IntentCallInvocationEnvelopeDto(
      id: id,
      qualifiedName: qualifiedName,
      arguments: arguments,
      source: source,
      createdAt: createdAt
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      qualifiedName,
      arguments,
      source,
      createdAt,
    ]
  }
  static func == (lhs: IntentCallInvocationEnvelopeDto, rhs: IntentCallInvocationEnvelopeDto) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsIntentCallPlatformBridge(lhs.id, rhs.id) && deepEqualsIntentCallPlatformBridge(lhs.qualifiedName, rhs.qualifiedName) && deepEqualsIntentCallPlatformBridge(lhs.arguments, rhs.arguments) && deepEqualsIntentCallPlatformBridge(lhs.source, rhs.source) && deepEqualsIntentCallPlatformBridge(lhs.createdAt, rhs.createdAt)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("IntentCallInvocationEnvelopeDto")
    deepHashIntentCallPlatformBridge(value: id, hasher: &hasher)
    deepHashIntentCallPlatformBridge(value: qualifiedName, hasher: &hasher)
    deepHashIntentCallPlatformBridge(value: arguments, hasher: &hasher)
    deepHashIntentCallPlatformBridge(value: source, hasher: &hasher)
    deepHashIntentCallPlatformBridge(value: createdAt, hasher: &hasher)
  }
}

/// Native entity-open envelope drained from the entity snapshot store.
///
/// Generated class from Pigeon that represents data sent in messages.
struct IntentCallEntityOpenEnvelopeDto: Hashable {
  var id: String
  var entityType: String
  var entityId: String
  var source: String
  var createdAt: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> IntentCallEntityOpenEnvelopeDto? {
    let id = pigeonVar_list[0] as! String
    let entityType = pigeonVar_list[1] as! String
    let entityId = pigeonVar_list[2] as! String
    let source = pigeonVar_list[3] as! String
    let createdAt = pigeonVar_list[4] as! String

    return IntentCallEntityOpenEnvelopeDto(
      id: id,
      entityType: entityType,
      entityId: entityId,
      source: source,
      createdAt: createdAt
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      entityType,
      entityId,
      source,
      createdAt,
    ]
  }
  static func == (lhs: IntentCallEntityOpenEnvelopeDto, rhs: IntentCallEntityOpenEnvelopeDto) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsIntentCallPlatformBridge(lhs.id, rhs.id) && deepEqualsIntentCallPlatformBridge(lhs.entityType, rhs.entityType) && deepEqualsIntentCallPlatformBridge(lhs.entityId, rhs.entityId) && deepEqualsIntentCallPlatformBridge(lhs.source, rhs.source) && deepEqualsIntentCallPlatformBridge(lhs.createdAt, rhs.createdAt)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("IntentCallEntityOpenEnvelopeDto")
    deepHashIntentCallPlatformBridge(value: id, hasher: &hasher)
    deepHashIntentCallPlatformBridge(value: entityType, hasher: &hasher)
    deepHashIntentCallPlatformBridge(value: entityId, hasher: &hasher)
    deepHashIntentCallPlatformBridge(value: source, hasher: &hasher)
    deepHashIntentCallPlatformBridge(value: createdAt, hasher: &hasher)
  }
}

/// Manifest-projected entity field keys for snapshot CRUD and search.
///
/// Generated class from Pigeon that represents data sent in messages.
struct IntentCallEntityKeyBundle: Hashable {
  var idKey: String
  var titleKey: String
  var subtitleKey: String
  var keywordsKey: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> IntentCallEntityKeyBundle? {
    let idKey = pigeonVar_list[0] as! String
    let titleKey = pigeonVar_list[1] as! String
    let subtitleKey = pigeonVar_list[2] as! String
    let keywordsKey = pigeonVar_list[3] as! String

    return IntentCallEntityKeyBundle(
      idKey: idKey,
      titleKey: titleKey,
      subtitleKey: subtitleKey,
      keywordsKey: keywordsKey
    )
  }
  func toList() -> [Any?] {
    return [
      idKey,
      titleKey,
      subtitleKey,
      keywordsKey,
    ]
  }
  static func == (lhs: IntentCallEntityKeyBundle, rhs: IntentCallEntityKeyBundle) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsIntentCallPlatformBridge(lhs.idKey, rhs.idKey) && deepEqualsIntentCallPlatformBridge(lhs.titleKey, rhs.titleKey) && deepEqualsIntentCallPlatformBridge(lhs.subtitleKey, rhs.subtitleKey) && deepEqualsIntentCallPlatformBridge(lhs.keywordsKey, rhs.keywordsKey)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("IntentCallEntityKeyBundle")
    deepHashIntentCallPlatformBridge(value: idKey, hasher: &hasher)
    deepHashIntentCallPlatformBridge(value: titleKey, hasher: &hasher)
    deepHashIntentCallPlatformBridge(value: subtitleKey, hasher: &hasher)
    deepHashIntentCallPlatformBridge(value: keywordsKey, hasher: &hasher)
  }
}

private class IntentCallPlatformBridgePigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return IntentCallInvocationEnvelopeDto.fromList(self.readValue() as! [Any?])
    case 130:
      return IntentCallEntityOpenEnvelopeDto.fromList(self.readValue() as! [Any?])
    case 131:
      return IntentCallEntityKeyBundle.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class IntentCallPlatformBridgePigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? IntentCallInvocationEnvelopeDto {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? IntentCallEntityOpenEnvelopeDto {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? IntentCallEntityKeyBundle {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class IntentCallPlatformBridgePigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return IntentCallPlatformBridgePigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return IntentCallPlatformBridgePigeonCodecWriter(data: data)
  }
}

class IntentCallPlatformBridgePigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = IntentCallPlatformBridgePigeonCodec(readerWriter: IntentCallPlatformBridgePigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol IntentCallInvocationsHostApi {
  func takePendingInvocations() throws -> [IntentCallInvocationEnvelopeDto]
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class IntentCallInvocationsHostApiSetup {
  static var codec: FlutterStandardMessageCodec { IntentCallPlatformBridgePigeonCodec.shared }
  /// Sets up an instance of `IntentCallInvocationsHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: IntentCallInvocationsHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let takePendingInvocationsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.intentcall_bridge.IntentCallInvocationsHostApi.takePendingInvocations\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      takePendingInvocationsChannel.setMessageHandler { _, reply in
        do {
          let result = try api.takePendingInvocations()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      takePendingInvocationsChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol IntentCallEntitiesHostApi {
  func upsertEntitySnapshots(entityType: String, snapshots: [[String?: Any?]], keys: IntentCallEntityKeyBundle) throws -> Int64
  func deleteEntitySnapshots(entityType: String, ids: [String], keys: IntentCallEntityKeyBundle) throws -> Int64
  func clearEntityTypeSnapshots(entityType: String) throws -> Int64
  func listEntitySnapshots(entityType: String) throws -> [[String?: Any?]]
  func searchEntitySnapshots(entityType: String, query: String, limit: Int64, keys: IntentCallEntityKeyBundle) throws -> [[String?: Any?]]
  func takePendingEntityOpens() throws -> [IntentCallEntityOpenEnvelopeDto]
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class IntentCallEntitiesHostApiSetup {
  static var codec: FlutterStandardMessageCodec { IntentCallPlatformBridgePigeonCodec.shared }
  /// Sets up an instance of `IntentCallEntitiesHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: IntentCallEntitiesHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let upsertEntitySnapshotsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.intentcall_bridge.IntentCallEntitiesHostApi.upsertEntitySnapshots\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      upsertEntitySnapshotsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let entityTypeArg = args[0] as! String
        let snapshotsArg = args[1] as! [[String?: Any?]]
        let keysArg = args[2] as! IntentCallEntityKeyBundle
        do {
          let result = try api.upsertEntitySnapshots(entityType: entityTypeArg, snapshots: snapshotsArg, keys: keysArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      upsertEntitySnapshotsChannel.setMessageHandler(nil)
    }
    let deleteEntitySnapshotsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.intentcall_bridge.IntentCallEntitiesHostApi.deleteEntitySnapshots\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      deleteEntitySnapshotsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let entityTypeArg = args[0] as! String
        let idsArg = args[1] as! [String]
        let keysArg = args[2] as! IntentCallEntityKeyBundle
        do {
          let result = try api.deleteEntitySnapshots(entityType: entityTypeArg, ids: idsArg, keys: keysArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      deleteEntitySnapshotsChannel.setMessageHandler(nil)
    }
    let clearEntityTypeSnapshotsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.intentcall_bridge.IntentCallEntitiesHostApi.clearEntityTypeSnapshots\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      clearEntityTypeSnapshotsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let entityTypeArg = args[0] as! String
        do {
          let result = try api.clearEntityTypeSnapshots(entityType: entityTypeArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      clearEntityTypeSnapshotsChannel.setMessageHandler(nil)
    }
    let listEntitySnapshotsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.intentcall_bridge.IntentCallEntitiesHostApi.listEntitySnapshots\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      listEntitySnapshotsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let entityTypeArg = args[0] as! String
        do {
          let result = try api.listEntitySnapshots(entityType: entityTypeArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      listEntitySnapshotsChannel.setMessageHandler(nil)
    }
    let searchEntitySnapshotsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.intentcall_bridge.IntentCallEntitiesHostApi.searchEntitySnapshots\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      searchEntitySnapshotsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let entityTypeArg = args[0] as! String
        let queryArg = args[1] as! String
        let limitArg = args[2] as! Int64
        let keysArg = args[3] as! IntentCallEntityKeyBundle
        do {
          let result = try api.searchEntitySnapshots(entityType: entityTypeArg, query: queryArg, limit: limitArg, keys: keysArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      searchEntitySnapshotsChannel.setMessageHandler(nil)
    }
    let takePendingEntityOpensChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.intentcall_bridge.IntentCallEntitiesHostApi.takePendingEntityOpens\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      takePendingEntityOpensChannel.setMessageHandler { _, reply in
        do {
          let result = try api.takePendingEntityOpens()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      takePendingEntityOpensChannel.setMessageHandler(nil)
    }
  }
}
