// Autogenerated from Pigeon (v26.3.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package dev.intentcall.intentcall_platform

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object IntentCallPlatformBridgePigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/**
 * Native invocation envelope drained from the handoff store.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class IntentCallInvocationEnvelopeDto (
  val id: String,
  val qualifiedName: String,
  val arguments: Map<String?, Any?>? = null,
  val source: String,
  val createdAt: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): IntentCallInvocationEnvelopeDto {
      val id = pigeonVar_list[0] as String
      val qualifiedName = pigeonVar_list[1] as String
      val arguments = pigeonVar_list[2] as Map<String?, Any?>?
      val source = pigeonVar_list[3] as String
      val createdAt = pigeonVar_list[4] as String
      return IntentCallInvocationEnvelopeDto(id, qualifiedName, arguments, source, createdAt)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      qualifiedName,
      arguments,
      source,
      createdAt,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as IntentCallInvocationEnvelopeDto
    return IntentCallPlatformBridgePigeonUtils.deepEquals(this.id, other.id) && IntentCallPlatformBridgePigeonUtils.deepEquals(this.qualifiedName, other.qualifiedName) && IntentCallPlatformBridgePigeonUtils.deepEquals(this.arguments, other.arguments) && IntentCallPlatformBridgePigeonUtils.deepEquals(this.source, other.source) && IntentCallPlatformBridgePigeonUtils.deepEquals(this.createdAt, other.createdAt)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + IntentCallPlatformBridgePigeonUtils.deepHash(this.id)
    result = 31 * result + IntentCallPlatformBridgePigeonUtils.deepHash(this.qualifiedName)
    result = 31 * result + IntentCallPlatformBridgePigeonUtils.deepHash(this.arguments)
    result = 31 * result + IntentCallPlatformBridgePigeonUtils.deepHash(this.source)
    result = 31 * result + IntentCallPlatformBridgePigeonUtils.deepHash(this.createdAt)
    return result
  }
}

/**
 * Native entity-open envelope drained from the entity snapshot store.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class IntentCallEntityOpenEnvelopeDto (
  val id: String,
  val entityType: String,
  val entityId: String,
  val source: String,
  val createdAt: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): IntentCallEntityOpenEnvelopeDto {
      val id = pigeonVar_list[0] as String
      val entityType = pigeonVar_list[1] as String
      val entityId = pigeonVar_list[2] as String
      val source = pigeonVar_list[3] as String
      val createdAt = pigeonVar_list[4] as String
      return IntentCallEntityOpenEnvelopeDto(id, entityType, entityId, source, createdAt)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      entityType,
      entityId,
      source,
      createdAt,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as IntentCallEntityOpenEnvelopeDto
    return IntentCallPlatformBridgePigeonUtils.deepEquals(this.id, other.id) && IntentCallPlatformBridgePigeonUtils.deepEquals(this.entityType, other.entityType) && IntentCallPlatformBridgePigeonUtils.deepEquals(this.entityId, other.entityId) && IntentCallPlatformBridgePigeonUtils.deepEquals(this.source, other.source) && IntentCallPlatformBridgePigeonUtils.deepEquals(this.createdAt, other.createdAt)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + IntentCallPlatformBridgePigeonUtils.deepHash(this.id)
    result = 31 * result + IntentCallPlatformBridgePigeonUtils.deepHash(this.entityType)
    result = 31 * result + IntentCallPlatformBridgePigeonUtils.deepHash(this.entityId)
    result = 31 * result + IntentCallPlatformBridgePigeonUtils.deepHash(this.source)
    result = 31 * result + IntentCallPlatformBridgePigeonUtils.deepHash(this.createdAt)
    return result
  }
}

/**
 * Manifest-projected entity field keys for snapshot CRUD and search.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class IntentCallEntityKeyBundle (
  val idKey: String,
  val titleKey: String,
  val subtitleKey: String,
  val keywordsKey: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): IntentCallEntityKeyBundle {
      val idKey = pigeonVar_list[0] as String
      val titleKey = pigeonVar_list[1] as String
      val subtitleKey = pigeonVar_list[2] as String
      val keywordsKey = pigeonVar_list[3] as String
      return IntentCallEntityKeyBundle(idKey, titleKey, subtitleKey, keywordsKey)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      idKey,
      titleKey,
      subtitleKey,
      keywordsKey,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as IntentCallEntityKeyBundle
    return IntentCallPlatformBridgePigeonUtils.deepEquals(this.idKey, other.idKey) && IntentCallPlatformBridgePigeonUtils.deepEquals(this.titleKey, other.titleKey) && IntentCallPlatformBridgePigeonUtils.deepEquals(this.subtitleKey, other.subtitleKey) && IntentCallPlatformBridgePigeonUtils.deepEquals(this.keywordsKey, other.keywordsKey)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + IntentCallPlatformBridgePigeonUtils.deepHash(this.idKey)
    result = 31 * result + IntentCallPlatformBridgePigeonUtils.deepHash(this.titleKey)
    result = 31 * result + IntentCallPlatformBridgePigeonUtils.deepHash(this.subtitleKey)
    result = 31 * result + IntentCallPlatformBridgePigeonUtils.deepHash(this.keywordsKey)
    return result
  }
}
private open class IntentCallPlatformBridgePigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          IntentCallInvocationEnvelopeDto.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          IntentCallEntityOpenEnvelopeDto.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          IntentCallEntityKeyBundle.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is IntentCallInvocationEnvelopeDto -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is IntentCallEntityOpenEnvelopeDto -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is IntentCallEntityKeyBundle -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface IntentCallInvocationsHostApi {
  fun takePendingInvocations(): List<IntentCallInvocationEnvelopeDto>

  companion object {
    /** The codec used by IntentCallInvocationsHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      IntentCallPlatformBridgePigeonCodec()
    }
    /** Sets up an instance of `IntentCallInvocationsHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: IntentCallInvocationsHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.intentcall_bridge.IntentCallInvocationsHostApi.takePendingInvocations$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.takePendingInvocations())
            } catch (exception: Throwable) {
              IntentCallPlatformBridgePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface IntentCallEntitiesHostApi {
  fun upsertEntitySnapshots(entityType: String, snapshots: List<Map<String?, Any?>>, keys: IntentCallEntityKeyBundle): Long
  fun deleteEntitySnapshots(entityType: String, ids: List<String>, keys: IntentCallEntityKeyBundle): Long
  fun clearEntityTypeSnapshots(entityType: String): Long
  fun listEntitySnapshots(entityType: String): List<Map<String?, Any?>>
  fun searchEntitySnapshots(entityType: String, query: String, limit: Long, keys: IntentCallEntityKeyBundle): List<Map<String?, Any?>>
  fun takePendingEntityOpens(): List<IntentCallEntityOpenEnvelopeDto>

  companion object {
    /** The codec used by IntentCallEntitiesHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      IntentCallPlatformBridgePigeonCodec()
    }
    /** Sets up an instance of `IntentCallEntitiesHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: IntentCallEntitiesHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.intentcall_bridge.IntentCallEntitiesHostApi.upsertEntitySnapshots$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val entityTypeArg = args[0] as String
            val snapshotsArg = args[1] as List<Map<String?, Any?>>
            val keysArg = args[2] as IntentCallEntityKeyBundle
            val wrapped: List<Any?> = try {
              listOf(api.upsertEntitySnapshots(entityTypeArg, snapshotsArg, keysArg))
            } catch (exception: Throwable) {
              IntentCallPlatformBridgePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.intentcall_bridge.IntentCallEntitiesHostApi.deleteEntitySnapshots$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val entityTypeArg = args[0] as String
            val idsArg = args[1] as List<String>
            val keysArg = args[2] as IntentCallEntityKeyBundle
            val wrapped: List<Any?> = try {
              listOf(api.deleteEntitySnapshots(entityTypeArg, idsArg, keysArg))
            } catch (exception: Throwable) {
              IntentCallPlatformBridgePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.intentcall_bridge.IntentCallEntitiesHostApi.clearEntityTypeSnapshots$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val entityTypeArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.clearEntityTypeSnapshots(entityTypeArg))
            } catch (exception: Throwable) {
              IntentCallPlatformBridgePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.intentcall_bridge.IntentCallEntitiesHostApi.listEntitySnapshots$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val entityTypeArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.listEntitySnapshots(entityTypeArg))
            } catch (exception: Throwable) {
              IntentCallPlatformBridgePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.intentcall_bridge.IntentCallEntitiesHostApi.searchEntitySnapshots$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val entityTypeArg = args[0] as String
            val queryArg = args[1] as String
            val limitArg = args[2] as Long
            val keysArg = args[3] as IntentCallEntityKeyBundle
            val wrapped: List<Any?> = try {
              listOf(api.searchEntitySnapshots(entityTypeArg, queryArg, limitArg, keysArg))
            } catch (exception: Throwable) {
              IntentCallPlatformBridgePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.intentcall_bridge.IntentCallEntitiesHostApi.takePendingEntityOpens$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.takePendingEntityOpens())
            } catch (exception: Throwable) {
              IntentCallPlatformBridgePigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
