import '../agent_manifest.dart';
import 'emitter_utils.dart';

/// Emits an Apple 27+ AppIntentsTesting UI-test scaffold.
///
/// This is the live-system proof lane: consuming apps add the emitted source to
/// an XCTest UI test target, install/launch the app, and run intents through the
/// App Intents testing infrastructure instead of calling `perform()` directly.
final class AppleAppIntentsTestingEmitter {
  const AppleAppIntentsTestingEmitter({
    required this.bundleIdentifier,
    this.testClassName = 'IntentCallAppIntentsLiveInvocationTests',
    this.sampleArguments = const <String, Map<String, Object?>>{},
  });

  final String bundleIdentifier;
  final String testClassName;

  /// Sample primitive parameter values keyed by manifest `qualifiedName`.
  ///
  /// Required App Intent parameters must be present here for generated live
  /// invocation tests to be runnable in a consuming app.
  final Map<String, Map<String, Object?>> sampleArguments;

  String emitUiTests(final AgentManifest manifest) {
    final tools = manifest.tools.toList();
    if (tools.isEmpty) {
      throw StateError('Apple App Intents testing requires at least one tool.');
    }

    final buffer = StringBuffer()
      ..writeln('// Generated by intentcall_platform — live proof scaffold.')
      ..writeln('// Add to an XCTest UI test target and run on macOS/iOS 27+.')
      ..writeln('#if canImport(AppIntentsTesting)')
      ..writeln('import AppIntentsTesting')
      ..writeln('import XCTest')
      ..writeln()
      ..writeln('@available(iOS 27.0, macOS 27.0, *)')
      ..writeln('final class $testClassName: XCTestCase {')
      ..writeln('  private var definitions: IntentDefinitions!')
      ..writeln()
      ..writeln('  override func setUp() async throws {')
      ..writeln('    try await super.setUp()')
      ..writeln('    continueAfterFailure = false')
      ..writeln('    await XCUIApplication().launch()')
      ..writeln(
        '    definitions = IntentDefinitions(bundleIdentifier: "${escapeSwiftString(bundleIdentifier)}")',
      )
      ..writeln('  }');

    for (final tool in tools) {
      _writeToolTest(buffer, tool);
    }

    buffer
      ..writeln('}')
      ..writeln('#endif');
    return buffer.toString();
  }

  void _writeToolTest(
    final StringBuffer buffer,
    final AgentManifestEntry tool,
  ) {
    final typeName = swiftIntentTypeName(tool.qualifiedName);
    final functionName = 'test${typeName}LiveInvocation';
    final typedResult = tool.inlineRuntime?.result;
    buffer
      ..writeln()
      ..writeln('  func $functionName() async throws {')
      ..writeln(
        '    let intent = definitions.intents["$typeName"].makeIntent(${_swiftSampleArguments(tool)})',
      )
      ..writeln('    let result = try await intent.run()');
    if (typedResult != null) {
      buffer
        ..writeln(
          '    let value: ${_swiftTypeForResult(typedResult.type)} = try result.value',
        )
        ..writeln('    _ = value');
    }
    buffer.writeln('  }');
  }

  String _swiftSampleArguments(final AgentManifestEntry tool) {
    final values = sampleArguments[tool.qualifiedName] ?? const {};
    final parameters = _swiftParameters(tool);
    final out = <String>[];
    for (final parameter in parameters) {
      final hasValue = values.containsKey(parameter.name);
      if (!hasValue && parameter.required) {
        throw UnsupportedError(
          'Missing sample argument "${parameter.name}" for '
          '${tool.qualifiedName}; AppIntentsTesting live invocation needs '
          'values for required parameters.',
        );
      }
      if (!hasValue) {
        continue;
      }
      out.add(
        '${parameter.variableName}: ${_swiftLiteral(values[parameter.name], parameter.schemaType, tool.qualifiedName, parameter.name)}',
      );
    }
    return out.join(', ');
  }
}

final class _LiveTestParameter {
  const _LiveTestParameter({
    required this.name,
    required this.variableName,
    required this.schemaType,
    required this.required,
  });

  final String name;
  final String variableName;
  final String schemaType;
  final bool required;
}

List<_LiveTestParameter> _swiftParameters(final AgentManifestEntry tool) {
  final properties = tool.inputSchema['properties'];
  if (properties is! Map) {
    return const <_LiveTestParameter>[];
  }
  final rawRequired = tool.inputSchema['required'];
  final required = <String>{
    ...(rawRequired is List ? rawRequired : const <Object?>[])
        .whereType<String>(),
  };
  final out = <_LiveTestParameter>[];
  for (final entry in properties.entries) {
    final name = '${entry.key}';
    final schema = entry.value;
    if (schema is! Map) {
      continue;
    }
    final schemaType = '${schema['type']}';
    if (_swiftTypeForSchema(schemaType) == null) {
      throw UnsupportedError(
        'Apple AppIntentsTesting scaffold supports only primitive '
        'string/integer/number/boolean parameters in ${tool.qualifiedName}; '
        '"$name" has unsupported type "$schemaType".',
      );
    }
    out.add(
      _LiveTestParameter(
        name: name,
        variableName: _swiftIdentifier(name),
        schemaType: schemaType,
        required: required.contains(name),
      ),
    );
  }
  return out;
}

String _swiftLiteral(
  final Object? value,
  final String schemaType,
  final String qualifiedName,
  final String parameterName,
) {
  final invalid = UnsupportedError(
    'Sample argument "$parameterName" for $qualifiedName must match '
    'schema type "$schemaType".',
  );
  return switch (schemaType) {
    'string' when value is String => '"${escapeSwiftString(value)}"',
    'integer' when value is int => '$value',
    'number' when value is num => value.toDouble().toString(),
    'boolean' when value is bool => '$value',
    _ => throw invalid,
  };
}

String? _swiftTypeForSchema(final String type) => switch (type) {
  'string' => 'String',
  'integer' => 'Int',
  'number' => 'Double',
  'boolean' => 'Bool',
  _ => null,
};

String _swiftTypeForResult(final AgentManifestInlineRuntimeResultType type) =>
    switch (type) {
      AgentManifestInlineRuntimeResultType.string => 'String',
      AgentManifestInlineRuntimeResultType.integer => 'Int',
      AgentManifestInlineRuntimeResultType.number => 'Double',
      AgentManifestInlineRuntimeResultType.boolean => 'Bool',
    };

String _swiftIdentifier(final String name) {
  final parts = name
      .split(RegExp('[^A-Za-z0-9]+'))
      .where((final p) => p.isNotEmpty);
  if (parts.isEmpty) {
    return 'value';
  }
  final first = parts.first;
  final rest = parts
      .skip(1)
      .map((final part) => '${part[0].toUpperCase()}${part.substring(1)}');
  final candidate = first + rest.join();
  final identifier = RegExp('^[A-Za-z_]').hasMatch(candidate)
      ? candidate
      : 'value$candidate';
  return _swiftReservedWords.contains(identifier)
      ? '`$identifier`'
      : identifier;
}

const _swiftReservedWords = <String>{
  'Any',
  'Protocol',
  'Self',
  'Type',
  'actor',
  'as',
  'associatedtype',
  'associativity',
  'async',
  'await',
  'break',
  'case',
  'catch',
  'class',
  'continue',
  'convenience',
  'default',
  'defer',
  'deinit',
  'didSet',
  'do',
  'dynamic',
  'else',
  'enum',
  'extension',
  'fallthrough',
  'false',
  'fileprivate',
  'final',
  'for',
  'func',
  'get',
  'guard',
  'if',
  'import',
  'in',
  'indirect',
  'infix',
  'init',
  'inout',
  'internal',
  'is',
  'isolated',
  'lazy',
  'left',
  'let',
  'mutating',
  'nil',
  'none',
  'nonisolated',
  'open',
  'operator',
  'optional',
  'override',
  'postfix',
  'precedence',
  'prefix',
  'private',
  'protocol',
  'public',
  'repeat',
  'required',
  'rethrows',
  'return',
  'right',
  'self',
  'set',
  'some',
  'static',
  'struct',
  'subscript',
  'super',
  'switch',
  'throw',
  'throws',
  'true',
  'try',
  'unowned',
  'var',
  'weak',
  'where',
  'while',
  'willSet',
};
