import '../agent_manifest.dart';
import 'emitter_utils.dart';

/// Emits Swift App Intents + shortcuts provider for iOS and macOS.
///
/// Logic mirrors [generateAppleAgentManifest] in `intentcall_apple`; this emitter
/// turns manifest rows into compile-time Swift for `Runner/Generated/`.
final class AppleSwiftAppIntentsEmitter {
  const AppleSwiftAppIntentsEmitter({this.fallbackProtocolScheme});

  final String? fallbackProtocolScheme;

  String emit(final AgentManifest manifest) {
    final protocolScheme = fallbackProtocolScheme ?? manifest.protocolScheme;
    final bridgeProtocolScheme =
        manifest.tools.any(
          (final tool) =>
              tool.dispatchMode == AgentManifestDispatchMode.openApp,
        )
        ? protocolScheme
        : null;
    final buffer = StringBuffer()
      ..writeln('// Generated by intentcall_platform — do not edit by hand.')
      ..writeln('import AppIntents')
      ..writeln('import Foundation')
      ..writeln('#if canImport(UIKit)')
      ..writeln('import UIKit')
      ..writeln('#elseif canImport(AppKit)')
      ..writeln('import AppKit')
      ..writeln('#endif')
      ..writeln();

    final shortcutLines = <String>[];
    for (final tool in manifest.tools) {
      if (tool.dispatchMode == AgentManifestDispatchMode.inlineRuntime) {
        throw UnsupportedError(
          'Apple inlineRuntime dispatch is not supported yet for '
          '${tool.qualifiedName}.',
        );
      }
      final typeName = swiftIntentTypeName(tool.qualifiedName);
      final title = escapeSwiftString(
        tool.description.isEmpty
            ? humanizeAgentName(tool.name)
            : tool.description,
      );
      final phrase = escapeSwiftString(humanizeAgentName(tool.name));
      final parameters = _swiftParameters(tool);
      final argumentLines = _swiftArgumentLines(parameters);
      final opensApp = tool.dispatchMode == AgentManifestDispatchMode.openApp;
      buffer
        ..writeln('@available(iOS 16.0, macOS 13.0, *)')
        ..writeln('struct $typeName: AppIntent {')
        ..writeln('  static var title: LocalizedStringResource = "$title"')
        ..writeln(
          '  static var openAppWhenRun: Bool = ${opensApp ? 'true' : 'false'}',
        )
        ..writeln();
      for (final parameter in parameters) {
        buffer
          ..writeln(
            '  @Parameter(title: "${escapeSwiftString(parameter.title)}")',
          )
          ..writeln('  var ${parameter.variableName}: ${parameter.swiftType}')
          ..writeln();
      }
      buffer
        ..writeln('  func perform() async throws -> some IntentResult {')
        ..writeln('    var arguments: [String: Any] = [:]');
      for (final line in argumentLines) {
        buffer.writeln('    $line');
      }
      buffer
        ..writeln(
          '    let invocationId = await IntentCallNativeBridge.enqueue(qualifiedName: "${escapeSwiftString(tool.qualifiedName)}", arguments: arguments, openApp: $opensApp)',
        )
        ..writeln(
          r'    return .result(dialog: IntentDialog("Queued invocation \(invocationId) for app dispatch."))',
        )
        ..writeln('  }')
        ..writeln('}')
        ..writeln();
      if (tool.surfaces.includes(
        AgentManifestSurface.appleAppShortcuts,
        defaultValue: false,
      )) {
        shortcutLines.add(
          '    AppShortcut(intent: $typeName(), phrases: ["\\(.applicationName) $phrase"])',
        );
      }
    }

    buffer
      ..writeln('@available(iOS 16.0, macOS 13.0, *)')
      ..writeln('struct IntentCallShortcutsProvider: AppShortcutsProvider {')
      ..writeln('  static var appShortcuts: [AppShortcut] {');
    if (shortcutLines.isEmpty) {
      buffer.writeln('    []');
    } else {
      shortcutLines.forEach(buffer.writeln);
    }
    buffer
      ..writeln('  }')
      ..writeln('}')
      ..writeln()
      ..writeln('enum IntentCallNativeHandoffStore {')
      ..writeln(
        '  private static let pendingKey = "intentcall.pending_invocations"',
      )
      ..writeln()
      ..writeln('  static func append(_ item: [String: Any]) {')
      ..writeln('    objc_sync_enter(UserDefaults.standard)')
      ..writeln('    defer { objc_sync_exit(UserDefaults.standard) }')
      ..writeln(
        '    var pending = UserDefaults.standard.array(forKey: pendingKey) as? [[String: Any]] ?? []',
      )
      ..writeln('    pending.append(item)')
      ..writeln('    UserDefaults.standard.set(pending, forKey: pendingKey)')
      ..writeln('  }')
      ..writeln('}')
      ..writeln()
      ..writeln('enum IntentCallNativeBridge {')
      ..writeln(
        '  private static let fallbackScheme: String? = ${_swiftOptionalString(bridgeProtocolScheme)}',
      )
      ..writeln()
      ..writeln(
        '  static func enqueue(qualifiedName: String, arguments: [String: Any], openApp: Bool) async -> String {',
      )
      ..writeln('    let invocationId = UUID().uuidString')
      ..writeln('    let item: [String: Any] = [')
      ..writeln('      "id": invocationId,')
      ..writeln('      "qualifiedName": qualifiedName,')
      ..writeln('      "arguments": arguments,')
      ..writeln('      "source": "native.generated",')
      ..writeln(
        '      "createdAt": ISO8601DateFormatter().string(from: Date())',
      )
      ..writeln('    ]')
      ..writeln('    IntentCallNativeHandoffStore.append(item)')
      ..writeln('    var allowedPath = CharacterSet.alphanumerics')
      ..writeln('    allowedPath.insert(charactersIn: "_-.~")')
      ..writeln(
        '    let encodedName = qualifiedName.addingPercentEncoding(withAllowedCharacters: allowedPath) ?? qualifiedName',
      )
      ..writeln(
        r'    guard openApp, let scheme = fallbackScheme, let url = URL(string: "\(scheme)://invoke/\(encodedName)") else { return invocationId }',
      )
      ..writeln('    #if canImport(UIKit)')
      ..writeln('    await UIApplication.shared.open(url)')
      ..writeln('    #elseif canImport(AppKit)')
      ..writeln('    NSWorkspace.shared.open(url)')
      ..writeln('    #endif')
      ..writeln('    return invocationId')
      ..writeln('  }')
      ..writeln('}');

    return buffer.toString();
  }
}

String _swiftOptionalString(final String? value) {
  final trimmed = value?.trim() ?? '';
  if (trimmed.isEmpty) {
    return 'nil';
  }
  requireProtocolScheme(trimmed, artifact: 'Apple fallback URL');
  return '"${escapeSwiftString(trimmed)}"';
}

final class _SwiftParameter {
  const _SwiftParameter({
    required this.name,
    required this.variableName,
    required this.title,
    required this.swiftType,
    required this.required,
  });

  final String name;
  final String variableName;
  final String title;
  final String swiftType;
  final bool required;
}

List<_SwiftParameter> _swiftParameters(final AgentManifestEntry tool) {
  final properties = tool.inputSchema['properties'];
  if (properties is! Map) {
    return const <_SwiftParameter>[];
  }
  final rawRequired = tool.inputSchema['required'];
  final required = <String>{
    ...(rawRequired is List ? rawRequired : const <Object?>[])
        .whereType<String>(),
  };
  final out = <_SwiftParameter>[];
  for (final entry in properties.entries) {
    final name = '${entry.key}';
    final schema = entry.value;
    if (schema is! Map) {
      continue;
    }
    final schemaType = '${schema['type']}';
    final baseType = _swiftTypeFor(schemaType);
    if (baseType == null) {
      throw UnsupportedError(
        'Apple App Intents support only primitive string/integer/number/boolean '
        'parameters in ${tool.qualifiedName}; "$name" has unsupported type '
        '"$schemaType".',
      );
    }
    final isRequired = required.contains(name);
    out.add(
      _SwiftParameter(
        name: name,
        variableName: _swiftIdentifier(name),
        title: humanizeAgentName(name),
        swiftType: isRequired ? baseType : '$baseType?',
        required: isRequired,
      ),
    );
  }
  return out;
}

List<String> _swiftArgumentLines(final List<_SwiftParameter> parameters) {
  final out = <String>[];
  for (final parameter in parameters) {
    if (parameter.required) {
      out.add(
        'arguments["${escapeSwiftString(parameter.name)}"] = ${parameter.variableName}',
      );
    } else {
      out.add(
        'if let value = ${parameter.variableName} { arguments["${escapeSwiftString(parameter.name)}"] = value }',
      );
    }
  }
  return out;
}

String? _swiftTypeFor(final String type) => switch (type) {
  'string' => 'String',
  'integer' => 'Int',
  'number' => 'Double',
  'boolean' => 'Bool',
  _ => null,
};

String _swiftIdentifier(final String name) {
  final parts = name
      .split(RegExp('[^A-Za-z0-9]+'))
      .where((final p) => p.isNotEmpty);
  if (parts.isEmpty) {
    return 'value';
  }
  final first = parts.first;
  final rest = parts
      .skip(1)
      .map((final part) => '${part[0].toUpperCase()}${part.substring(1)}');
  final candidate = first + rest.join();
  final identifier = RegExp('^[A-Za-z_]').hasMatch(candidate)
      ? candidate
      : 'value$candidate';
  return _swiftReservedWords.contains(identifier)
      ? '`$identifier`'
      : identifier;
}

const _swiftReservedWords = <String>{
  'Any',
  'Protocol',
  'Self',
  'Type',
  'actor',
  'as',
  'associatedtype',
  'associativity',
  'async',
  'await',
  'break',
  'case',
  'catch',
  'class',
  'continue',
  'convenience',
  'default',
  'defer',
  'deinit',
  'didSet',
  'do',
  'dynamic',
  'else',
  'enum',
  'extension',
  'fallthrough',
  'false',
  'fileprivate',
  'final',
  'for',
  'func',
  'get',
  'guard',
  'if',
  'import',
  'in',
  'indirect',
  'infix',
  'init',
  'inout',
  'internal',
  'is',
  'isolated',
  'lazy',
  'left',
  'let',
  'mutating',
  'nil',
  'none',
  'nonisolated',
  'open',
  'operator',
  'optional',
  'override',
  'postfix',
  'precedence',
  'prefix',
  'private',
  'protocol',
  'public',
  'repeat',
  'required',
  'rethrows',
  'return',
  'right',
  'self',
  'set',
  'some',
  'static',
  'struct',
  'subscript',
  'super',
  'switch',
  'throw',
  'throws',
  'true',
  'try',
  'unowned',
  'var',
  'weak',
  'where',
  'while',
  'willSet',
};
