import '../agent_manifest.dart';

/// Emits a Windows registry script for `intentcall://` protocol activation.
final class WindowsProtocolEmitter {
  const WindowsProtocolEmitter({
    this.protocolScheme = 'intentcall',
    this.exePlaceholder = '@APP_EXE@',
  });

  final String protocolScheme;
  final String exePlaceholder;

  String emit(final AgentManifest manifest) {
    final toolsComment = manifest.tools
        .map((final t) => '; tool: ${t.qualifiedName}')
        .join('\n');
    return '''
; Generated by intentcall_platform — do not edit by hand.
$toolsComment
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\\Software\\Classes\\$protocolScheme]
@="URL:IntentCall Protocol"
"URL Protocol"=""

[HKEY_CURRENT_USER\\Software\\Classes\\$protocolScheme\\shell\\open\\command]
@="\\"$exePlaceholder\\" \\"%1\\""
''';
  }

  /// MSIX `Extensions` fragment for protocol activation (optional packaging).
  String emitMsixFragment(final AgentManifest manifest) {
    final names = manifest.tools.map((final t) => t.qualifiedName).join(', ');
    return '''
<!-- Generated by intentcall_platform — do not edit by hand. -->
<!-- tools: $names -->
<uap:Extension Category="windows.protocol">
  <uap:Protocol Name="$protocolScheme">
    <uap:DisplayName>IntentCall</uap:DisplayName>
  </uap:Protocol>
</uap:Extension>
''';
  }
}
